[toolchain]
anchor_version = "0.30.1"
rust_version = "1.79.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap = "CHj59753iWLjmuEMjJcZc5Y2fztHaVTmHiRaxDk2dzR4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
